services:
  - type: web
    name: cocody-rugby-club
    env: docker
    plan: free
    envVars:
      - key: APP_ENV
        value: local
      - key: APP_NAME
        value: cocody-rugby-club
      - key: APP_KEY
        value: base64:DPf7hcfGl0hcWu5r8G3mOYfCA+CoZDvxItEf0rIYoio=
      - key: APP_DEBUG
        value: true
      - key: APP_URL
        value: https://cocody-rugby-club.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d0irncadbo4c738qh2jg-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: rugbyclub_data
      - key: DB_USERNAME
        value: rugbyclub_data_user
      - key: DB_PASSWORD
        value: JjvPaEHrEAFu81cjTKhNbaGiof0aLpX4
